### ISSUE TITLE
Student Profile Header

### ISSUE THREAD

**Issue by maso9613** [Saccoon/go-mahi-react#10]
On the Student-Profile page. 

The student profile header will include: 
- The student's name 
- The student's profession (if not profession and still a student, say "student")
- An edit button for the student to edit his profile
- A student profile card nav bar with six different options for viewing the student profile card ("Feed" will actually be called "Social Feed" with an icon different from the one shown in this image. View the Social Feed feature to view the correct icon.). The page that is selected on the student profile will be highlighted in in light blue text, with a blue icon, and a box that is darker than the other options in the nav bar.
![profile page-profile 1920 copy](https://user-images.githubusercontent.com/39073930/47369860-2cd8f300-d6aa-11e8-8fec-de21cc0423ae.png)

**Comment by Saccoon** [comment]
done
