### ISSUE TITLE
1 Empathy Interviews Video Overlay

### ISSUE THREAD

**Issue by maso9613** [Saccoon/go-mahi-react#36]
This is apart of the Student - Empathy Interviews milestone. 

The video will overlay the entire [page](https://github.com/Saccoon/go-mahi-react/issues/37) that is darkened substantially. The video will be centered on the user's screen. The student can choose to click outside of the video for the overlay to disappear. Also, the video overlay will automatically disappear and the rest of the site gain full brightness once the video reaches its end. 

The video player should allow the student to pick the speed at which the video is being played (slow-mo and fast pace options). Also, the player can give the student the option to play the video fullscreen. 

![empathy interview feedback - video tutorial](https://user-images.githubusercontent.com/39073930/48962632-c87aaf00-ef47-11e8-8273-8aecb3ea3811.png)

**Comment by Saccoon** [comment]
done
