### ISSUE TITLE
2 Phase 1.0 Intro Page Main Area

### ISSUE THREAD

**Issue by maso9613** [Saccoon/go-mahi-react#37]
This is apart of the Student - Empathy Interview milestone.

See picture below for reference. This is the page that the student sees after the video overlay goes away. This feature explains the main area, not the right sidebar.
![empathy interview feedback - portal](https://user-images.githubusercontent.com/39073930/48963029-e0eec780-ef4f-11e8-8d6a-b88dfa61458d.png)
The student can push enter on the keyboard or push the "Give Feedback" button to add interview information. In this case, the student will be taken to [the next page](https://github.com/Saccoon/go-mahi-react/issues/38) in Phase 1.0.

If he chooses not to add any interviews, he can click the underlined text that reads "Skip Interview Feedback". This will bring the student to the popup overlay below (this is not a new page but simple comes up over the existing orange part of the page). By clicking the "Phase 1.5" the student is brought to [Phase 1.5: Key Insights milestone](https://github.com/Saccoon/go-mahi-react/milestone/9), [this page](https://github.com/Saccoon/go-mahi-react/issues/58) to be more specific; by clicking "Back to interviews", the popup overlay disappears and the student is taken back to the "Phase 1.0 Intro Page Main Area". 

![empathy interview feedback - skip interview title page popup](https://user-images.githubusercontent.com/39073930/50363905-796a6e80-0533-11e9-8b7f-0a941ac9f018.png)

**Comment by Saccoon** [comment]
done
