### ISSUE TITLE
Right Sidebar Default Content & Button

### ISSUE THREAD

**Issue by maso9613** [Saccoon/go-mahi-react#40]
This is apart of the Student-Challenge Right Sidebar milestone.

The right sidebar, by default, has a few lines of text and a button. The text will be Phase specific, meaning that it will be based on the Phase (all pages within Phase 1.0 will have the same unique text, all pages within Phase 1.5 will have the same unique text, etc.). 

The button will also be phase specific. It will pull up the all text guide of that very Phase for the student without disrupting his main challenge area on the left. We will cover this guide in another feature.

The right sidebar below will be the default right sidebar for users. This will change when only when the user chooses to view the guide for that very Phase. Also, the styling may change slightly as the user changes the view setting of the sidebar. This will be covered in another feature.
![empathy interview feedback - portal](https://user-images.githubusercontent.com/39073930/48964954-fa583980-ef78-11e8-9365-a3bc042f36f0.png)

**Comment by Saccoon** [comment]
done
