### ISSUE TITLE
Right Sidebar Video Tutorial Icon & Text

### ISSUE THREAD

**Issue by maso9613** [Saccoon/go-mahi-react#41]
This is apart of the Student-Challenge Right Sidebar milestone.

The feature highlighted in the image below shows on all default views of the right sidebar. When a student clicks on either the play icon or the underlined text, the video tutorial for that very Phase will once again overlay the existing screen as the background is faded out (darkened). As said before, this video player should have the options to view the video in fullscreen and slow down or speedup the pace of the video. To get out of the video, the user simply clicks outside of the video.
![empathy interview feedback - portal](https://user-images.githubusercontent.com/39073930/48965012-49529e80-ef7a-11e8-9987-83507567f6c7.png)

The video will overlay the user's existing page. Reference the image below for how the video would appear.
![empathy interview feedback - video tutorial](https://user-images.githubusercontent.com/39073930/48965014-52dc0680-ef7a-11e8-8528-73b6a785ecb5.png)

**Comment by Saccoon** [comment]
done
