### ISSUE TITLE
Right Sidebar Bottom Previous/Next Step

### ISSUE THREAD

**Issue by maso9613** [Saccoon/go-mahi-react#43]
This is apart of the Student-Challenge Right Sidebar milestone.

At the bottom of the right sidebar there will always appear four areas for a student to click. This should always show at the bottom of the right sidebar, which should ideally allows show at the bottom of the user's screen. This means that, whenever the orange main challenge area is tall enough to take up the entire screen's height, the right sidebar should do the same. Put another way, the right sidebar should take up the user's entire right side of the browser's window with this feature always at the bottom of that sidebar (except for the top GoMahi.com nav bar).

The "Previous Step" and "Next Step" underlined text will bring the student to the most recent step or closest future step. This brings the users to the closest page within a Phase, not just the beginning of the closest Phase (i.e. a student on the page "Interview 2" would be taken back to "Interview 1", not just the "Phase 1.0 Empathy Interviews" page or the Challenge home page). All future steps that have yet to be viewed by the student after submitting the existing page will be inaccessible. When this is the case, the "Next Step" underlined text and arrows will be faded out in a lighter grey text. When a user hovers over one of these things of text (if active), the text and arrows will turn orange.
![empathy interview feedback - portal](https://user-images.githubusercontent.com/39073930/48965370-6dfe4480-ef81-11e8-8f0e-94b337994e7d.png)

Please note, as the user moves the the previous of next step, the right sidebar's content will not change unless the student moves into a whole other Phase (but obviously, the content in the user's orange main challenge area and the text in the right sidebar navigation dropdown will change to reflect the change in page). For example, if a student moves from "Interview 1" to "Interview 2", the right sidebar will keep up the default view or the Empathy Interview guide, whatever the user was already viewing. Once the user moves to "Phase 1.5" then the default view for "Phase 1.5" will appear in the right sidebar.

**Comment by Saccoon** [comment]
done
