### ISSUE TITLE
Right Sidebar Bottom Other Options Menu

### ISSUE THREAD

**Issue by maso9613** [Saccoon/go-mahi-react#44]
This is apart of the Student-Challenge Right Sidebar milestone.

At the bottom of the right sidebar there will always appear four areas for a student to click. This should always show at the bottom of the right sidebar, which should ideally allows show at the bottom of the user's screen. This means that, whenever the orange main challenge area is tall enough to take up the entire screen's height, the right sidebar should do the same. Put another way, the right sidebar should take up the user's entire right side of the browser's window with this feature always at the bottom of that sidebar (except for the top GoMahi.com nav bar).

The ellipsis on the bottom area of the right sidebar is the "More Options" button. When hovered over with the mouse, the ellipsis will turn orange and a dark box with the text "More Options" will appear briefly as long as the mouse is over the ellipsis. See the image directly below for reference.
![48965143-6046c000-ef7d-11e8-948f-03f4603ee2a9](https://user-images.githubusercontent.com/39073930/48965380-c6354680-ef81-11e8-8e5e-5fdbc8be8270.png)

The ellipsis, when clicked on, will bring up a menu for the user. This is the user's navigation for the right sidebar. The users can click "Main Empathy Interview Sidebar" (this text is Phase specific) to have the right sidebar display the default right sidebar view. Or, clicking the "Empathy Interview Guide" (once again, Phase specific text) will bring the user to the very top of that Phase's all text guide. The last option, "Video Tutorial" will once again pull up the video overlay with the darkened background. Even though the image below does not show this, if the user is already on the default right sidebar view, then the "Main Empathy Interview Sidebar" would be greyed out. View the image below to see how this menu should appear:
![empathy interview feedback - more options pop up](https://user-images.githubusercontent.com/39073930/48965384-cfbeae80-ef81-11e8-802e-68dcace7d190.png)

**Comment by Saccoon** [comment]
done
