### ISSUE TITLE
Right Sidebar Bottom View Options Menu

### ISSUE THREAD

**Issue by maso9613** [Saccoon/go-mahi-react#45]
This is apart of the Student-Challenge Right Sidebar milestone.

At the bottom of the right sidebar there will always appear four areas for a student to click. This should always show at the bottom of the right sidebar, which should ideally allows show at the bottom of the user's screen. This means that, whenever the orange main challenge area is tall enough to take up the entire screen's height, the right sidebar should do the same. Put another way, the right sidebar should take up the user's entire right side of the browser's window with this feature always at the bottom of that sidebar (except for the top GoMahi.com nav bar).

Lastly, the eye icon is an option for the user to change the width of the right sidebar. Once again hovering over this icon will cause it to turn orange and pop up a dark box with the text "Responsive View" to explain the purpose of the button. View image below for reference:
![empathy interview feedback - responsive view hover](https://user-images.githubusercontent.com/39073930/48965421-5a9fa900-ef82-11e8-8eb8-6049dcdd8e11.png)

Clicking the eye icon will bring up a menu to change the width of the right sidebar. There are four options shown in the image directly below. The right sidebar, by default, is at 25% width. Even though the image below does not show it, the user's current view option should be greyed out. The 100%, 50%, and 25% should all be rather self-explanatory. The only change that will happen to the sidebar is that, as the sidebar becomes wider, the text apart of the guide will get slightly larger. The orange main challenge area should automatically resize as the user changes view options.
![empathy interview feedback - responsive view popup](https://user-images.githubusercontent.com/39073930/48965418-51aed780-ef82-11e8-9913-61f0e6449ae7.png)

The "Full Portal Experience" option will make the sidebar go completely away. For the user to get the sidebar back, there will be an arrow in the right margin of the orange main challenge area that, when clicked on, will slide back out the right sidebar at 25% width of the screen.

**Comment by Saccoon** [comment]
done
