### ISSUE TITLE
Right Sidebar Phase Guide

### ISSUE THREAD

**Issue by maso9613** [Saccoon/go-mahi-react#46]
This is apart of the Student-Challenge Right Sidebar milestone.

When the student hits the dark button on the default right sidebar view to view the Phase-specific guide, the all text guide takes up nearly the entire right sidebar. View the image below for reference. The student can also make this happen by using the ellipsis "More Options" menu at the bottom of the right sidebar. 
![empathy interview feedback - empathy interview guide](https://user-images.githubusercontent.com/39073930/48965463-427c5980-ef83-11e8-9520-07c7b802870d.png)
For easier navigation, the right sidebar Phase Guide will have a simple table of contents like beginning. This will show all headers in the very guide and will bring the user to a specific part of the guide by clicking on the link. As stressed before, it is important that the the entire page does not reload and lose information from the orange main challenge area every the user takes an action the right sidebar.

**Comment by Saccoon** [comment]
done
