### ISSUE TITLE
Empathy Interview Top Progress Bar

### ISSUE THREAD

**Issue by maso9613** [Saccoon/go-mahi-react#47]
This is apart of the Student-Empathy Interview Milestone.

WE DO NOT WANT SIGNIFICANT TIME SPENT ON THE PROGRESS BAR FOR EACH CHALLENGE PAGE.  IT IS A NICE FEATURE BUT NOTHING THAT STUDENTS CAN'T LIVE WITHOUT. IF IT WILL TAKE MUCH TIME AT ALL, PLEASE TALK TO BOBBY OR I FIRST AND WE WILL DECIDE WHETHER OR NOT WE SHOULD MOVE FORWARD WITH IT.

At the top of each Phase there will be a bluish progress bar showing estimated progress on that very Phase. The progress is Phase-specific, meaning that it shows progress on just Phase 1.0. Once the users hits Phase 1.5, the progress bar restarts. 

Once the student is near the end of the Phase, the bar should extend across the entire orange main challenge area. We will estimate a total of six pages/steps in Phase 1.0... The "Phase 1.0 Empathy Interviews" page, "Interview 1", "Interview 2", "Interview 3", "Interview 4", and "Interview 5". Only once the user gets to Interview 6 will the bar be all the way full.

If this bar is difficult or would take any substantial amount of time to create/design, we should drop it and can add it later. Please lmk if this is the case, because it is not at all critical but a nice touch.
![empathy interview feedback - empathy interview guide](https://user-images.githubusercontent.com/39073930/48965511-64c2a700-ef84-11e8-9603-5e55e6ae6ba5.png)

**Comment by Saccoon** [comment]
done
