### ISSUE TITLE
Up & Down Arrows

### ISSUE THREAD

**Issue by maso9613** [Saccoon/go-mahi-react#48]
This is apart of the Student-Empathy Interviews Milestone. This will be a feature on all other challenge step pages that are long enough to scroll through.

Clicking these arrows will gracefully bring the user to the next or previous field. The field the user is brought to will become centered on the user's screen vertically. Please note, user's are able to freely scroll through pages. AKA the site will not automatically adjust a field to the center or top of the user's screen. It will only occur when the arrows are clicked on. 
![empathy interview feedback - empathy interview guide](https://user-images.githubusercontent.com/39073930/48965594-de0ec980-ef85-11e8-81b8-d0365c150436.png)

**Comment by Saccoon** [comment]
done
