### ISSUE TITLE
Company Challenges

### ISSUE THREAD

**Issue by maso9613** [Saccoon/go-mahi-react#5]
This feature displays all of the company's challenges on GoMahi.com. Depending on the filter applied above, the challenges displayed within this feature will change to show all challenges, active challenges, or judged/completed projects. 

At the bottom of this feature there is a LAUNCH A NEW CHALLENGE NOW button for companies to be redirected to the launch new challenge page.

NOTE: If a company has less than four challenges under a certain filter, the challenge cards should be left-aligned. If a company has zero challenges then the area remains without any challenge cards with the orange "LAUNCH CHALLENGE NOW" button filling the now empty area.
![company-all projects 1920](https://user-images.githubusercontent.com/39073930/47967400-73bbd680-e022-11e8-8fe6-bb823965e448.png)

The challenge cards will slightly change based on whether or not the challenge is active, ready to be judged, or already judged. View the image below to see how the three different cards will look: 
![company-all projects 1920](https://user-images.githubusercontent.com/39073930/47967750-8e904a00-e026-11e8-95f4-5cbeee8a1273.png)

- For those challenge cards for challenges that have already been judged, mark them as "Judged" with the date that the challenge was fully judged.

- For those challenge cards for challenges that have been closed but not yet judged, mark them as "REVIEW NOW!" with the date at which we ask them to finish review by. For now, we are uncertain the amount of time we will give them to review.

**Comment by Saccoon** [comment]
Make "Load More" scrollable instead of button press
