### ISSUE TITLE
My Active Challenges Area

### ISSUE THREAD

**Issue by maso9613** [Saccoon/go-mahi-react#7]
This area exists in the Student-Challenges Page.
This area sits below the challenge filters and contains a view of all of the user's Active Challenges.
This area is shown when the "My Active Challenges" button is selected above.

Within this area there are no additional filters for the user. This is because, for now, users are only able to take part in one challenge at a time. Users must first submit a challenge before starting a new one. 

The challenge cards for the "My Active Challenges" area will remain similar to the cards that show on the "Live Challenges" area. See the picture below for reference (this picture shows the live challenges area, which will show cards the same as the cards in the "My Active Challenges" area except with likely just a maximum of one card).
![student-all projects 1920](https://user-images.githubusercontent.com/39073930/47969285-f94b8080-e03a-11e8-8bc3-75d69f2b27e4.png)

The area is infinitely scrollable.

**Comment by Saccoon** [comment]
Make "Load More" scrollable instead of button press

**Comment by Saccoon** [comment]
Darken Section Gray Hashes

**Comment by Saccoon** [comment]
Done, keeping button, and darkened background
