### ISSUE TITLE
Left Sidebar

### ISSUE THREAD

**Issue by maso9613** [Saccoon/go-mahi-react#9]
On the Student-Profile page. The Left Sidebar has four main areas in it: 

1. An orange button that redirects the student to his referral/reward page.
2. The user's ranking on the site based on total points earned thus far.
3. The user's college.
4. An area where the student can view his completed or active (enrolled in) projects thus far.*** 

***These cards under "YOUR PROJECTS" should show an image uploaded by the company for the challenge and includes a maximum of three lines of text from the actual challenge. Clicking on one of these cards will give the student a view of the challenge with info relating to how he did on that very challenge. 

***Depending on the size of the student profile card, there will be either one or two "YOUR PROJECTS" cards displayed at any given time. There will be a link under these challenge cards for the student to view more of his completed or active challenges on the Student-Challenges page. If he has no completed or active challenges, have this area change to a view of live challenges on GoMahi.com with the top labeled "Live Challenges" instead of "Your Challenges". 

![profile page-profile 1920 copy](https://user-images.githubusercontent.com/39073930/47369422-40378e80-d6a9-11e8-8f11-ca2c0a4f7321.png)

**Comment by Saccoon** [comment]
Active and completed challenges show up as "Projects"

**Comment by Saccoon** [comment]
done
